server:
  port: 1008

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  application:
    name: GATEWAYSERVER
  #security:
    #oauth2:
      #resourceserver:
        #jwt:
          #jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#      - id: customersModule
##       uri: http://localhost:1004/
#        uri: lb://CUSTOMERS
#        predicates:
#        - Path=/c/**
#      - id: friendsModule
##       uri: http://localhost:1003/
#        uri: lb://FRIENDS
#        predicates:
#        - Path=/f/**
#      - id: plansModule
##       uri: http://localhost:1002/
#        uri: lb://PLANS
#        predicates:
#        - Path=/p/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1007/eureka/